CI: Add series file check
Ensure all patch files in the repository have been referenced.

If the patch is to be excluded, it should exist in 'series' anyway but
remain commented out (#).

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,16 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
+    - name: Check series file
+      run: |
+        for patch in $(ls *.patch); do
+            grep "$patch" series
+            if [ $? != 0 ]; then
+                echo "::error title=$patch::Patch is missing from series file"
+                exit 1
+            fi
+        done
+
     - name: Get GTK Version
       run: |
         source PKGBUILD
